### ISSUE TITLE
How should the diagnosis server be implemented ?

### ISSUE THREAD

**Issue by bhushanRamnani** [google/exposure-notifications-android#12]
It's not clear whether the back-end diagnosis server that is used for storage and retrieval of diagnosis keys can be implemented by App developers or will it be provided as a cloud service by Google ? In case it needs to be implemented by App developers, does the API mandate a specific query format or app developers are allowed to choose whatever format they prefer ? 

As per the exposure key file format, seems like the apps will be able to download in batches. Does that mean the query parameters should contain timestamp ranges and batch number ?

https://static.googleusercontent.com/media/www.google.com/en//covid19/exposurenotifications/pdfs/Exposure-Key-File-Format-and-Verification.pdf

**Comment by tjohns** [comment]
Hello,
The back-end server needs to be implemented by app developers.

A reference design is available here as an example: https://github.com/google/exposure-notifications-server

The query parameter format for downloading keys from the backend server is entirely up to the app developer, since this is outside the scope of the protocol specification.
