### ISSUE TITLE
Why is Bluetooth and Internet Permission needed

### ISSUE THREAD

**Issue by sec293484** [google/exposure-notifications-android#29]
The Exposure Notification Framework API (implemented as Play Framework) is listening for data sent via Bluetooth. The app is can just start/stop this functionality and can request data/sates via the API for more information but the Framework runs the whole bluetooth related code. Why does the app need Bluetooth and Internet permission if it does do any bluetooth related tasks? The permissions should only be bound to the PlayFramework not the the app...

**Comment by nic0lette** [comment]
Thank you for your question.

You're correct that Google Play Services manages all the bluetooth communications for the app, but the API was implemented in such a way that the app must still request the [BLUETOOTH permission](https://developer.android.com/reference/android/Manifest.permission#BLUETOOTH). Since this is a "normal" permission, it is automatically granted.

As far as why INTERNET permission is required, that's because the app would need to connect to a server via the Internet in order to download Diagnosis Keys.

**Comment by jixiangox** [comment]
Diagnosis Keys can only be downloaded from an internet-accessible Diagnosis Key Server.

It’s required to verify before release.

In Scan flow, we cannot distinguish ID and TEK in RF. There are no field in service data to do so.

It’s impossible to send TEK(s) through RF w/o a connect.
