### ISSUE TITLE
Exposure_notification_api not found

### ISSUE THREAD

**Issue by erotundo** [google/exposure-notifications-android#3]
Hi!

I'm trying to run the reference version from your code (i downloaded to Android Studio) i did the compilation and runs but i get this error

I test this in 2 android phones (Android 10 and Android 8) with latest version of play store

> com.google.android.gms.common.api.ApiException: 17: API: Nearby.EXPOSURE_NOTIFICATION_API is not available on this device. Connection failed with: ConnectionResult{statusCode=API_UNAVAILABLE, resolution=null, message=null}
>         at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(com.google.android.gms:play-services-base@@17.2.1:4)
>         at com.google.android.gms.common.api.internal.ApiExceptionMapper.getException(com.google.android.gms:play-services-base@@17.2.1:2)
>         at com.google.android.gms.common.api.internal.zah.zaa(com.google.android.gms:play-services-base@@17.2.1:18)
>         at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zaa(com.google.android.gms:play-services-base@@17.2.1:204)
>         at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zac(com.google.android.gms:play-services-base@@17.2.1:210)
>         at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zaa(com.google.android.gms:play-services-base@@17.2.1:108)
>         at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.onConnectionFailed(com.google.android.gms:play-services-base@@17.2.1:75)
>         at com.google.android.gms.common.api.internal.zabn.run(com.google.android.gms:play-services-base@@17.2.1:17)
>         at android.os.Handler.handleCallback(Handler.java:883)
>         at android.os.Handler.dispatchMessage(Handler.java:100)
>         at com.google.android.gms.internal.base.zap.dispatchMessage(com.google.android.gms:play-services-base@@17.2.1:8)
>         at android.os.Looper.loop(Looper.java:237)
>         at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by pkleczko** [comment]
@erotundo are you part of beta developers group with access to Exposure Notification? if not currently you will not be able to use API with a production GPS

**Comment by ayoubphy** [comment]
> @erotundo are you part of beta developers group with access to Exposure Notification? if not currently you will not be able to use API with a production GPS

Let's say we are the developers tasked with 
building this app for our country, How do we apply to join the group of beta developers with access to the API ?

**Comment by pkleczko** [comment]
Your country Health Authority should contact Google/Apple directly to get access.

**Comment by ayoubphy** [comment]
Is there some contact form or a specific contact channel for our public health authorities to contact google directly ?

I checked this link but it's for the play store app review team https://support.google.com/googleplay/android-developer/contact/expo_notif_api
Is it the one to use ?

**Comment by tjohns** [comment]
As noted above, the Play Services module required to access this code is currently being provided to public health agencies on a pre-release basis.

If you are associated with a government public health agency, this is the form to request access:

https://support.google.com/googleplay/android-developer/contact/expo_notif_api

**This form should be completed only by representatives of government public health agencies.**

**Comment by indrasenakatam** [comment]
HI all,
I am getting this below exception. 
17: API: Nearby.EXPOSURE_NOTIFICATION_API is not available on this device. Connection failed with: ConnectionResult{statusCode=API_UNAVAILABLE, resolution=null, message=null}.

As described above,  android app code google play-services required access from public health agencies. As like that, do we have to follow these steps..? Could please suggest 

**1**: we need to provide advance notice to the Google Play App Review team to use Exposure API's

**2**: after got the access, can we test  Exposure API's locally while developing app or required to access with step 1 credentials only. Because source-code does not have any configurations to access and validations

Could you please suggest on this..? please excuse if anything is wrong from my end

**Comment by mlocati** [comment]
> Your country Health Authority should contact Google/Apple directly to get access.

It makes no sense to me. Bending Spoons, the company in charge to develop Immuni (the [official contact tracing app for Italy](http://www.salute.gov.it/portale/nuovocoronavirus/dettaglioNotizieNuovoCoronavirus.jsp?lingua=italiano&menu=notizie&p=dalministero&id=4513)) has just published its [source code](https://github.com/immuni-app/immuni-app-android).

Being an open source project, every interested developer should be able to test it, so there should be a way to install the Exposure Notification even for people that are not officially involved in it.

**Comment by pkleczko** [comment]
Source code is not enough to make it working. Your app's package name and signing certificate details need to be approved.

**Comment by MakariKevin** [comment]
Hi @tjohns 

I was able to:
1. Successfully install Google Play Services (v20.15.55) on my Android test device
2. Install the Apollo Test App (exposure_notification_test_20200428-060252.apk)
3. Import the Exposure Notification SDK into an Android app project

However, I'm unable to proceed with the rest of the implementation since the referenced classes in this sample design are not available in the local maven-repository SDK as per the documentation [https://drive.google.com/file/d/1Sbtt8ZQ6wvI4TJJ4LoHEVdu8gzXj4MI7/view?usp=sharing](url). An example is the class _ExposureNotificationClientWrapper_ that contains a call to start the Exposure Notifications API.

More over, I have tried running this particular example on the same device but throws the below stack-trace upon pressing the **TURN ON** button from the _OnboardingPermissionFragment_ screen:

`2020-06-07 12:45:50.753 30177-30485/com.google.android.apps.exposurenotification W/GoogleApiManager: com.google.android.gms.internal.nearby.zzq could not execute call because it requires feature (nearby_exposure_notification, 2).
2020-06-07 12:45:50.760 30177-30485/com.google.android.apps.exposurenotification W/GoogleApiAvailability: GMS core API Availability. ConnectionResult=2, tag=null
    java.lang.IllegalArgumentException
        at com.google.android.gms.common.GoogleApiAvailability.zaa(com.google.android.gms:play-services-base@@17.2.1:141)
        at com.google.android.gms.common.GoogleApiAvailability.zaa(com.google.android.gms:play-services-base@@17.2.1:46)
        at com.google.android.gms.common.api.internal.GoogleApiManager.zac(com.google.android.gms:play-services-base@@17.2.1:213)
        at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zab(com.google.android.gms:play-services-base@@17.2.1:180)
        at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zabg(com.google.android.gms:play-services-base@@17.2.1:112)
        at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zabe(com.google.android.gms:play-services-base@@17.2.1:40)
        at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.onConnected(com.google.android.gms:play-services-base@@17.2.1:19)
        at com.google.android.gms.common.internal.zag.onConnected(com.google.android.gms:play-services-base@@17.2.1:2)
        at com.google.android.gms.common.internal.BaseGmsClient$zzf.zzm(com.google.android.gms:play-services-basement@@17.2.1:24)
        at com.google.android.gms.common.internal.BaseGmsClient$zza.zza(com.google.android.gms:play-services-basement@@17.2.1:12)
        at com.google.android.gms.common.internal.BaseGmsClient$zzc.zzo(com.google.android.gms:play-services-basement@@17.2.1:11)
        at com.google.android.gms.common.internal.BaseGmsClient$zzb.handleMessage(com.google.android.gms:play-services-basement@@17.2.1:49)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at com.google.android.gms.internal.common.zzi.dispatchMessage(com.google.android.gms:play-services-basement@@17.2.1:8)
        at android.os.Looper.loop(Looper.java:226)
        at android.os.HandlerThread.run(HandlerThread.java:65)`

Kindly note that we were commissioned by MOH - Government of Kenya, to develop a Covid-19 contact tracing mobile solution and therefore we have access to the Google Drive folder containing the Beta resources.

Thank you!

**Comment by Akefhabbal** [comment]
> As noted above, the Play Services module required to access this code is currently being provided to public health agencies on a pre-release basis.
> 
> If you are associated with a government public health agency, this is the form to request access:
> 
> https://support.google.com/googleplay/android-developer/contact/expo_notif_api
> 
> **This form should be completed only by representatives of government public health agencies.**

What is the format of the documentation that is needed by PHA? Is there an example that we can fill and ask the PHA to sign it?
